language: node_js
node_js:
  - "6.0"
  - "6"
  - "5.0"
  - "5"
env:
  global:
    - MONGODB_VERSION=2.6.12
before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - mongo --version
  - mongod --version
  - npm install -g npm@latest
  - npm install -g bower
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install
before_script:
  - sleep 15
script:
  - npm test
